-- Enable needed extensions
create extension if not exists pgcrypto;

-- Profiles table to store user metadata
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  avatar text, -- 用户头像URL
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Artifacts master data（全局奇物数据源）
create table if not exists public.artifacts (
  id text primary key,
  name text not null,
  era text,
  location text,
  story text,
  collection_tags text[] default '{}',
  base_value int default 0,
  image text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_artifacts_tags on public.artifacts using gin (collection_tags);

-- Rooms table
create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  short_id text unique, -- 6位数字ID，用于方便查找
  owner_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'waiting', -- waiting / playing / ended
  name text, -- 房间名称
  max_players int default 6, -- 最大玩家数
  description text, -- 房间描述
  invite_code text, -- 邀请码
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 全局拍卖表（与房间无关）
create table if not exists public.auctions (
  id text primary key,
  artifact_id text not null,
  artifact jsonb,
  highest_bid int default 0,
  highest_bidder uuid,
  time_remaining int default 30,
  status text not null default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_auctions_status on public.auctions(status);

-- 全局拍卖历史（可选，与房间无关）
create table if not exists public.auction_history (
  id bigint generated by default as identity primary key,
  auction_id text not null,
  artifact_id text not null,
  artifact jsonb,
  winner uuid,
  winning_bid int,
  created_at timestamptz default now()
);

-- 添加索引以提高查询性能
create index if not exists idx_rooms_short_id on public.rooms(short_id);
create index if not exists idx_rooms_status on public.rooms(status);
create index if not exists idx_rooms_owner_id on public.rooms(owner_id);

-- Room players
create table if not exists public.room_players (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'player', -- owner / player
  energy int not null default 50,
  is_ready boolean not null default false,
  joined_at timestamptz default now(),
  unique(room_id, user_id)
);

-- Optional: Artifacts owned by players in a room
create table if not exists public.room_artifacts (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  owner_user_id uuid references auth.users(id) on delete set null,
  artifact_id text not null,
  created_at timestamptz default now()
);

-- Items master data（全局道具数据源）
create table if not exists public.items (
  id text primary key,
  name text not null,
  type text not null, -- 功能分类，如 buff / control / special
  price int not null,
  effect text not null, -- 与前端效果枚举对齐，如 return_artifact / cancel_auction / extend_time / steal_energy / double_auction
  image text,
  description text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- RLS policies (enable if needed)
-- alter table public.rooms enable row level security;
-- alter table public.room_players enable row level security;
-- alter table public.room_artifacts enable row level security;
-- create policy "room owner or member can read room" on public.rooms for select using (
--   auth.uid() = owner_id or exists(select 1 from public.room_players rp where rp.room_id = rooms.id and rp.user_id = auth.uid())
-- );
